algoritmo "FazSomaProcedimento"
// Função : Passagem de Parametro [POR VALOR]
// Autor : Marcos Fernando Borges
// Data : 20/02/2020
// Seção de Declarações: Pratica 02 - Curso em Video

var
X, Y: Inteiro

Procedimento soma(A,B: inteiro)
Inicio

   Escreval ("Recebi o valor de: " , A)
   Escreval ("Recebi o valor de: " , B)
   Escreval ("A Soma entre " , A , " e " , B , " = " , A+B)


FimProcedimento


inicio
// Seção de Comandos 

X <- 5
Y <- 8

soma (x,y)


fimalgoritmo
